spring:
  application:
    name: order-service
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:25432/postgres}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"
  jpa:
    open-in-view: false
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: "${RABBITMQ_PORT:5672}"
    username: "${RABBITMQ_USERNAME:guest}"
    password: "${RABBITMQ_PASSWORD:guest}"


server:
  port: 8082
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full

#### Queue config ####
order:
  order-event-exchange: order-exchange
  new-order-queue: new-order
  delivered-order-queue: delivered-order
  cancelled-order-queue: cancelled-order
  error-order-queue: error-order
